services:
  frontend:
    build:
      context: ui
      target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
